### ISSUE TITLE
[FR] `Participants`

### ISSUE THREAD

**Issue by sarpik** [sarpik/turbo-schedule#57]
This is largely caused & inspired by https://github.com/sarpik/turbo-schedule/issues/60

From

`lesson.students` field  of `string[]`

to

`lesson.participats` with `Array<{ labels: Array<enum>, text: string, isEmpty: boolean }>`

...probably?

This would be done internally, inside the scraper, once the things are being scraped. And would probably be saved into the database this way too. The API itself would probably remain (mostly) the same, while also allowing getting a raw response without any modifications.

Furthermore, I'm considering having a single field in the database `participants` that would replace `students`, `classes`, `teachers` & `rooms`. This would allow simplier filtering, populating of lessons etc.; the API could still have separate endpoints for each field.

---

Also related - should we make `lesson.teacher` & `lesson.room` strings into string arrays? Probably yes, since there can be >1 teacher & >1 room

---

See also https://github.com/sarpik/turbo-schedule/issues/41

**Comment by sballl** [comment]
I think we can change `lessons.students` to `lessons.participants`. This change would make these fields more accurate

**Comment by sarpik** [comment]
@sballl I'm thinking the same.

What about the `lesson.teacher` & `lesson.room` fields? Would the have any use anymore?
I think that for convenience we can still keep them.

---

But at this point, it looks like we'll need a version 2 of the API - since the scraper now collects all types of participants (students, classes, teachers, rooms), things've changed quite a lot.

For example, a lesson might have more than 1 teacher (& even >1 room, because of the non-determinism @ upstream we scrape from).
In this case, I'd like to have an array of strings both for `teachers` & `rooms`, instead of having them in a single string, separated by a `,`.

I'm pretty sure it'd be easier for both of us to have the `/api/v2` endpoint & migrate our user-facing apps at our own pace, incrementally.

I'd like to implement https://github.com/sarpik/turbo-schedule/issues/41 before starting the design of `API v2` - there might be something new I'll discover. After that's done, we can discuss the `API v2` in more detail (or if we even need it) - I'll keep you posted.

**Comment by sarpik** [comment]
F#ck, the database grows 10x in size because of this:D

**Comment by sarpik** [comment]
lol, since I've fixed the `teachers` & `rooms` thingie, empty lessons now have quite a lot of peeps in them xd We'll need to adjust, you'll need to do that aswell @sballl :D 

![image](https://user-images.githubusercontent.com/29430509/80327748-ce17ab00-8845-11ea-8daa-3ddec7c06044.png)

**Comment by sarpik** [comment]
Alright,

1. I'm keeping the `/api/v1` backwards compatible

I do not want to have such a hurdle both maintaining the 2 separate versions & also updating everything instantly - both here, and in the mobile apps (would force @sballl to update at exactly the same time as us - no goodies!)

2. `/api/v1/participant` will be available!

See https://github.com/sarpik/turbo-schedule/pull/69
